export const PRICE_LABELS = {
    c4_azul: { label: 'Ficha C4 Azul', cat: 'RENIEC', icon: 'article' },
    inscripcion: { label: 'Ficha de Inscripcion', cat: 'RENIEC', icon: 'assignment' },
    virtual_azul: { label: 'DNI Azul Virtual', cat: 'RENIEC', icon: 'credit_card' },
    virtual_electronico: { label: 'DNI Electronico Virtual', cat: 'RENIEC', icon: 'contact_page' },
    amarillo: { label: 'DNI Amarillo Virtual', cat: 'RENIEC', icon: 'credit_card' },
    familiares_pdf: { label: 'Familiares PDF + Fotos (Antiguo)', cat: 'Familiares', icon: 'family_restroom' },
    familiares_arbol_visual: { label: 'Ver Familiares (PDF + Fotos)', cat: 'Familiares', icon: 'account_tree' },
    familiares_texto: { label: 'Familiares Texto', cat: 'Familiares', icon: 'family_restroom' },
    numeros_dni: { label: 'Ver Numeros de un DNI', cat: 'Telefonos', icon: 'phone_in_talk' },
    info_linea: { label: 'Informacion Completa Linea', cat: 'Telefonos', icon: 'sim_card' },
    verificador_op: { label: 'Verificador de Operadora', cat: 'Telefonos', icon: 'wifi_calling' },
    titular_numero: { label: 'Consulta Titular del Numero', cat: 'Telefonos', icon: 'contact_phone' },
    dni_premium: { label: 'RENIEC Premium (C4 + Biometria)', cat: 'RENIEC', icon: 'verified' },
    busqueda_nombres: { label: 'Busqueda por Nombres', cat: 'RENIEC', icon: 'person_search' },
    dni_gratis: { label: 'Busqueda por DNI (Gratis)', cat: 'RENIEC', icon: 'badge' },
    fiscalia_dni: { label: 'Fiscalia por DNI', cat: 'Denuncias', icon: 'gavel' },
    fiscalia_nombre: { label: 'Fiscalia por Nombres', cat: 'Denuncias', icon: 'gavel' },
    fiscalia_ruc: { label: 'Fiscalia por RUC', cat: 'Denuncias', icon: 'gavel' },
    fiscalia_caso: { label: 'Informacion Caso Fiscal', cat: 'Denuncias', icon: 'gavel' },
    busqueda_facial: { label: 'Busqueda Facial IA', cat: 'Facial', icon: 'face' },
    antecedentes_policiales: { label: 'Certificado de Antecedentes Policiales', cat: 'Certificados', icon: 'policy' },
    antecedentes_penales: { label: 'Certificado de Antecedentes Penales', cat: 'Certificados', icon: 'gavel' },
    antecedentes_judiciales: { label: 'Certificado de Antecedentes Judiciales', cat: 'Certificados', icon: 'account_balance' },
    dni: { label: 'Denuncias por DNI', cat: 'Denuncias', icon: 'badge' },
    antper: { label: 'Antecedentes Global', cat: 'Denuncias', icon: 'gavel' },
    placa: { label: 'Denuncias por Placa', cat: 'Vehiculos', icon: 'directions_car' },
    record_vehicular: { label: 'Record Vehicular', cat: 'Vehiculos', icon: 'directions_car' },
    daily_reward: { label: 'Creditos Gratuitos Diarios', cat: 'Sistema', icon: 'card_giftcard' },
};
