from backend.parser import parse_bot_response
import json

text = """
[ #𝗦𝗜𝗧𝗘𝗫 𝗗𝗔𝗧𝗔 ] ➤ #RENIECFULL

❯ DNI: 72928271 - 1
❯ EDAD: 33
❯ SEXO: MASCULINO
❯ NOMBRES: LUIS ENRIQUE
❯ APELLIDOS: CARRASCO TANTACHUCO

[ INFO PERSONAL ]

❯ ESTATURA: 1.73 M
❯ RESTRICCIÓN: NINGUNA
❯ ESTADO CIVIL: SOLTERO
❯ EMISIÓN: 04/06/2018
❯ CADUCIDAD: 04/06/2026
❯ INSCRIPCIÓN: 02/12/2008
❯ GRADO INST: SECUNDARIA-5TO AÑO

[ NACIMIENTO ]

❯ DISTRITO: CHICLAYO
❯ PROVINCIA: CHICLAYO
❯ DEPARTAMENTO: LAMBAYEQUE
❯ FECHA: 20/03/1992

[ DIRECCIONES ]

❯ DISTRITO: CHICLAYO
❯ PROVINCIA: CHICLAYO
❯ DEPARTAMENTO: LAMBAYEQUE
❯ DIRECCIÓN: CALLE ANGAMOS 454 URB. EL PORVENIR

[ EXTRAS ]

❯ PADRE: CARRASCO SILVA LUIS MIGUEL
❯ MADRE: TANTACHUCO MARTINEZ  MARIA DEL ROSARIO
❯ DECLARANTE: N/A
❯ ÓRGANOS: NO

[ BALANCE ]
➜ USUARIO: 8287794268
➜ CREDITOS: ∞
➜ NOMBRE: Ivi

By: @Sitexdata_bot
"""

data = parse_bot_response(text)
print(json.dumps(data, indent=2))
